CC = gcc
LFLAGS = -g -Werror -Wextra -Wall
LINK = -lm -lGL -lGLU -lglut 
DEBUG = -g
NAME = main
FILE = main.cpp
MODULE = point.cpp
MODULE1 = figure.cpp

all:
	$(CC) $(DEBUG) $(LINK) $(LFLAGS) $(MODULE) $(MODULE1) $(FILE) -o $(NAME) && ./$(NAME)



